treatments = [
  "Mouth care",
  "Bath",
  "Nail cutting",
  "Shaving",
  "Condom catheterization & training",
  "Nelcath catheterization & training",
  "Foley's catheterization",
  "Foley's catheter care",
  "Suprapubic catheterization",
  "Suprapubic catheter care",
  "Perennial care",
  "Bladder wash with normal saline",
  "Bladder wash with soda bicarbonate",
  "Enema",
  "High enema",
  "Suppository",
  "Digital evacuation",
  "Ryles tube insertion",
  "Ryles tube care",
  "Ryles tube feeding & training",
  "PEG care",
  "Wound care",
  "Wound care training to family",
  "Suture removal",
  "Vacuum dressing",
  "Tracheostomy care",
  "Colostomy care",
  "Colostomy irrigation care",
  "ileostomy care",
  "Urostomy care",
  "Upper limb lymphedema bandaging",
  "Lower limb lymphedema bandaging",
  "Upper limb lymphedema hosiery",
  "IV fluid infusion",
  "IV medicine bolus administration",
  "IV cannula care",
  "S/C fluid infusion (subcutaneous)",
  "S/C medicine bolus administration",
  "S/C cannula care",
  "Ascites tapping",
  "Ascitic catheter care",
]

treatments.each do |t|
  Treatment.create!(
    name: t,
  )
end
