// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Multiselect$Arike from "../Multi-select-dropdown/Multiselect.bs.js";

var root = document.querySelector("#DetailedExample");

if (!(root == null)) {
  ReactDom.render(React.createElement(Multiselect$Arike.MinimalExample.make, {}), root);
}

export {
  
}
/* root Not a pure module */
