// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as AutoComplete$Arike from "./AutoComplete/AutoComplete.bs.js";

function s(prim) {
  return prim;
}

function runReact(param) {
  var root = document.querySelector("#root");
  if (!(root == null)) {
    ReactDom.render(React.createElement(AutoComplete$Arike.make, {
              getFilteredArray: (function (inputValue) {
                  return [
                            "emma",
                            "david",
                            "brian",
                            "robert",
                            "kiwyoski",
                            "heugo",
                            "droka",
                            "daran",
                            "eugi"
                          ].filter(function (el) {
                              return el.includes(inputValue);
                            });
                })
            }), root);
    return ;
  }
  
}

export {
  s ,
  runReact ,
  
}
/* react Not a pure module */
