// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

var RootElementMissing = /* @__PURE__ */Caml_exceptions.create("Domutils-Arike.RootElementMissing");

function focus(id) {
  var el = document.getElementById(id);
  var tmp;
  if (el !== undefined) {
    tmp = Caml_option.valFromOption(el);
  } else {
    throw {
          RE_EXN_ID: RootElementMissing,
          _1: id,
          Error: new Error()
        };
  }
  tmp.focus();
  
}

export {
  RootElementMissing ,
  focus ,
  
}
/* No side effect */
