module Treatment = PatientTreatment__Treatment
module TreatmentHistory = PatientTreatment__TreatmentHistory
module DropdownOption = PatientTreatment__DropdownOption
module DropdownOptionGroup = PatientTreatment__DropdownOptionGroup
