type t = {
  patient_at_peace: string,
  pain: string,
  shortness_breath: string,
  weakness: string,
  poor_mobility: string,
  nausea: string,
  vomiting: string,
  poor_appetite: string,
  constipation: string,
  sore: string,
  drowsiness: string,
  wound: string,
  lack_of_sleep: string,
  micturition: string,
}
let make = () => {
  patient_at_peace: "",
  pain: "",
  shortness_breath: "",
  weakness: "",
  poor_mobility: "",
  nausea: "",
  vomiting: "",
  poor_appetite: "",
  constipation: "",
  sore: "",
  drowsiness: "",
  wound: "",
  lack_of_sleep: "",
  micturition: "",
}
