// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Js_json from "bs-platform/lib/es6/js_json.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function s(prim) {
  return prim;
}

function make(id, word) {
  return {
          id: id,
          name: word
        };
}

function id(t) {
  return t.id;
}

function name(t) {
  return t.name;
}

var Record = {
  make: make,
  id: id,
  name: name
};

function AutoComplete(Props) {
  var id = Props.id;
  var api = Props.api;
  var name = Props.name;
  var labelOpt = Props.label;
  var placeholderOpt = Props.placeholder;
  var valueOpt = Props.value;
  var label = labelOpt !== undefined ? labelOpt : "Enter";
  var placeholder = placeholderOpt !== undefined ? placeholderOpt : "Start searching";
  var value = valueOpt !== undefined ? valueOpt : "";
  var match = React.useState(function () {
        return value;
      });
  var setInputValue = match[1];
  var inputValue = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setRenderSuggestions = match$1[1];
  var match$2 = React.useState(function () {
        return [];
      });
  var setSg = match$2[1];
  var sg = match$2[0];
  var createSuggestionArrayReducer = function (acc, current) {
    var idNameArray = Js_dict.entries(Belt_Option.getWithDefault(Js_json.decodeObject(current), {}));
    var match = Caml_array.get(idNameArray, 0);
    var match$1 = Caml_array.get(idNameArray, 1);
    var idValue = Belt_Option.getWithDefault(Js_json.decodeString(match[1]), "");
    var nameValue = Belt_Option.getWithDefault(Js_json.decodeString(match$1[1]), "");
    if (idValue !== "" && nameValue !== "") {
      return Belt_Array.concat(acc, [{
                    id: idValue,
                    name: nameValue
                  }]);
    } else {
      return acc;
    }
  };
  React.useEffect((function () {
          Promise.resolve(fetch(api).then(function (prim) {
                            return prim.json();
                          }).then(function (json) {
                          return Promise.resolve(Js_json.decodeArray(json));
                        }).then(function (opt) {
                        return Promise.resolve(Belt_Option.getWithDefault(opt, [null]));
                      }).then(function (items) {
                      var suggestionsList = Belt_Array.reduce(items, [], createSuggestionArrayReducer);
                      return Promise.resolve(Curry._1(setSg, (function (param) {
                                        return suggestionsList;
                                      })));
                    }).then(function (opt) {
                    return Promise.resolve(opt);
                  }));
          
        }), []);
  var getFilteredArray = function (input) {
    if (input === "") {
      return sg;
    } else {
      return sg.filter(function (info) {
                  return info.name.trim().toLocaleLowerCase().includes(input.trim().toLocaleLowerCase());
                });
    }
  };
  var getSuggestions = function (input) {
    var sg = Belt_Array.map(getFilteredArray(input), (function (w) {
            return {
                    id: w.id,
                    name: w.name
                  };
          }));
    if (sg.length < 1) {
      return React.createElement("div", {
                  className: "w-full absolute rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none text-sm text-center py-2"
                }, "No Matches Found");
    } else {
      return React.createElement("div", {
                  "aria-labelledby": "options-menu",
                  className: "z-10 w-full max-h-32 overflow-y-scroll absolute rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5",
                  role: "menu"
                }, React.createElement("ul", {
                      "aria-label": "menu",
                      className: "py-1",
                      role: "menu"
                    }, Belt_Array.map(sg, (function (word) {
                            return React.createElement("li", {
                                        key: word.id,
                                        className: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 focus:bg-gray-100 hover:text-gray-900",
                                        id: word.name,
                                        role: "menuitem",
                                        tabIndex: 0,
                                        onKeyDown: (function ($$event) {
                                            if ($$event.key === "Enter") {
                                              Curry._1(setInputValue, (function (param) {
                                                      return word.name;
                                                    }));
                                              return Curry._1(setRenderSuggestions, (function (param) {
                                                            return false;
                                                          }));
                                            }
                                            
                                          }),
                                        onClick: (function (param) {
                                            Curry._1(setInputValue, (function (param) {
                                                    return word.name;
                                                  }));
                                            return Curry._1(setRenderSuggestions, (function (param) {
                                                          return false;
                                                        }));
                                          })
                                      }, word.name);
                          }))));
    }
  };
  return React.createElement("div", {
              className: "bg-white"
            }, React.createElement("div", {
                  className: "w-full"
                }, React.createElement("div", {
                      className: "relative"
                    }, React.createElement("label", {
                          className: "block text-sm font-medium text-gray-700",
                          htmlFor: "email"
                        }, label), React.createElement("div", {
                          className: "mt-1"
                        }, React.createElement("input", {
                              "aria-describedby": "disease-description",
                              className: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md",
                              id: id,
                              tabIndex: 0,
                              autoComplete: "off",
                              name: name,
                              placeholder: placeholder,
                              type: "search",
                              value: inputValue,
                              onBlur: (function (param) {
                                  return Curry._1(setRenderSuggestions, (function (param) {
                                                return false;
                                              }));
                                }),
                              onChange: (function ($$event) {
                                  var value = $$event.target.value;
                                  return Curry._1(setInputValue, (function (param) {
                                                return value;
                                              }));
                                }),
                              onClick: (function (param) {
                                  return Curry._1(setRenderSuggestions, (function (param) {
                                                return true;
                                              }));
                                })
                            })), match$1[0] === true ? getSuggestions(inputValue) : React.createElement(React.Fragment, undefined))));
}

var make$1 = AutoComplete;

export {
  s ,
  Record ,
  make$1 as make,
  
}
/* react Not a pure module */
