// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Nanoid from "nanoid";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function s(prim) {
  return prim;
}

function make(word) {
  return {
          id: Nanoid.nanoid(),
          word: word
        };
}

function id(t) {
  return t.id;
}

function word(t) {
  return t.word;
}

var Record = {
  make: make,
  id: id,
  word: word
};

function AutoComplete(Props) {
  var options = Props.options;
  var match = React.useState(function () {
        return "";
      });
  var setInputValue = match[1];
  var inputValue = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setRenderSuggestions = match$1[1];
  var options$1 = Belt_Array.map(options, (function (w) {
          return {
                  id: Nanoid.nanoid(),
                  word: w
                };
        }));
  var getSuggestions = function (input) {
    var sg = options$1.filter(function (word) {
          return word.word.includes(input);
        });
    return React.createElement("div", {
                "aria-labelledby": "options-menu",
                className: "w-full rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none",
                role: "menu"
              }, React.createElement("div", {
                    "aria-expanded": true,
                    className: "py-1",
                    role: "none"
                  }, Belt_Array.map(sg, (function (word) {
                          return React.createElement("li", {
                                      key: word.id,
                                      className: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900",
                                      role: "menuitem",
                                      tabIndex: 0,
                                      onFocus: (function (param) {
                                          return Curry._1(setInputValue, (function (param) {
                                                        return word.word;
                                                      }));
                                        }),
                                      onClick: (function (param) {
                                          Curry._1(setInputValue, (function (param) {
                                                  return word.word;
                                                }));
                                          return Curry._1(setRenderSuggestions, (function (param) {
                                                        return false;
                                                      }));
                                        })
                                    }, word.word);
                        }))));
  };
  return React.createElement("div", {
              className: "p-8 flex items-center justify-center bg-white"
            }, React.createElement("div", {
                  className: "w-full max-w-xs mx-auto"
                }, React.createElement("div", undefined, React.createElement("label", {
                          className: "block text-sm font-medium text-gray-700",
                          htmlFor: "email"
                        }, "Email"), React.createElement("div", {
                          className: "mt-1"
                        }, React.createElement("input", {
                              "aria-describedby": "email-description",
                              className: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md",
                              id: "email",
                              tabIndex: 0,
                              name: "email",
                              placeholder: "you@example.com",
                              type: "text",
                              value: inputValue,
                              onChange: (function ($$event) {
                                  return Curry._1(setInputValue, (function (param) {
                                                var value = $$event.target.value;
                                                var len = value.length;
                                                if (len > 1) {
                                                  Curry._1(setRenderSuggestions, (function (param) {
                                                          return true;
                                                        }));
                                                } else {
                                                  Curry._1(setRenderSuggestions, (function (param) {
                                                          return false;
                                                        }));
                                                }
                                                return $$event.target.value;
                                              }));
                                })
                            })), match$1[0] === true ? getSuggestions(inputValue) : React.createElement(React.Fragment, undefined))));
}

var make$1 = AutoComplete;

export {
  s ,
  Record ,
  make$1 as make,
  
}
/* react Not a pure module */
